# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../00_card.ipynb 3
suits = ["♣️","♦️","❤️","♠️"]
ranks = [None, "A"] + [str(x) for x in range(2,11)]  + ["J", "Q", "K"]


# %% ../00_card.ipynb 6
"""
class Card:
    "A Playing Card"
    def __init__(self,
                 suit:int, # Index to 'suit'
                 rank:int):# Index to 'rank'
        self.suit,self.rank=suit,rank
    def __str__(self): return f"{suits[self.suit]} {ranks[self.rank]}"
    __repr__=__str__
"""

    

# %% ../00_card.ipynb 15
class Card:
    "A Playing Card"
    def __init__(self,
                 suit:int, # Index to 'suit'
                 rank:int):# Index to 'rank'
        self.suit,self.rank=suit,rank
    def __str__(self): return f"{suits[self.suit]} {ranks[self.rank]}"
    __repr__=__str__

# %% ../00_card.ipynb 21
class Card:
    "A Playing Card"
    def __init__(self,
                 suit:int, # Index to 'suit'
                 rank:int):# Index to 'rank'
        self.suit,self.rank=suit,rank
    def __str__(self): return f"{suits[self.suit]} {ranks[self.rank]}"
    def __eq__(self,a): return (self.suit,self.rank) == (a.suit,self.rank)
    __repr__=__str__

# %% ../00_card.ipynb 27
class Card:
    "A Playing Card"
    def __init__(self,
                 suit:int, # Index to 'suit'
                 rank:int):# Index to 'rank'
        self.suit,self.rank=suit,rank
    def __str__(self): return f"{suits[self.suit]} {ranks[self.rank]}"
    __repr__=__str__
